Prabvenu
ALU-CloudBand/tosca-docs-generator pull request #1
Opened 2017-04-01 15:38 UTC by prabvenu

2017-04-01 16:34 UTC, MosheElisha requested changes

2017-04-01 16:34 UTC, MosheElisha commented on src/test/java/org/tosca/docs/generators/html/HtmlGeneratorTest.java
> +    //@Test
Please uncomment and make sure it passes.
This method verifies that the generated HTML is valid.

2017-04-01 16:34 UTC, MosheElisha commented on src/main/java/org/tosca/docs/model/InterfaceMethod.java
> +     String getName();
Please make sure the "reformat code", "rearrange code" and other goodies are enabled in your IntelliJ commit dialog.
Please run it on the changed classes.

2017-04-01 16:34 UTC, MosheElisha commented on src/main/java/org/tosca/docs/generators/html/HtmlGenerator.java
> +        HashMap<String,String>  derivedFromDetails=new HashMap<String,String>();
You can use Guava Table here for a sleeker solution

2017-04-01 16:34 UTC, MosheElisha commented on src/main/resources/org/tosca/docs/messages.properties
> +headers.interfaces=Interfaces
I think these should also be added to the custom messages file.
The custom messages is used in a test that verifies that all the string labels are replaceable. 
Please also include the interfaces section in the i18n test

2017-04-03 09:01 UTC, prabvenu commented on src/main/resources/org/tosca/docs/messages.properties
> +headers.interfaces=Interfaces
I couldnt find place testcase for i18n test.

2017-04-03 11:20 UTC, MosheElisha approved these changes

2017-04-03 11:20 UTC, merged